# Generated by Django 5.2.5 on 2025-12-08 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnbindingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_subscriber_id', models.IntegerField(help_text='Subscriber ID user was previously bound to')),
                ('previous_binding_token', models.CharField(blank=True, help_text='Token that was used for original binding', max_length=32, null=True)),
                ('previous_bound_at', models.DateTimeField(blank=True, help_text='When the original binding occurred', null=True)),
                ('unbinding_reason', models.CharField(help_text='Reason for unbinding', max_length=100)),
                ('unbound_at', models.DateTimeField(help_text='When the unbinding occurred')),
                ('unbound_by', models.ForeignKey(blank=True, help_text='Admin user who performed the unbinding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_unbindings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unbinding_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unbinding Audit Log',
                'verbose_name_plural': 'Unbinding Audit Logs',
                'db_table': 'unbinding_audit_logs',
                'ordering': ['-unbound_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bound_subscriber_id', models.IntegerField(blank=True, db_index=True, help_text='Permanently bound subscriber ID after one-time token validation', null=True)),
                ('binding_token', models.CharField(blank=True, help_text='Token used for initial binding (for audit purposes)', max_length=32, null=True)),
                ('bound_at', models.DateTimeField(blank=True, help_text='Timestamp when user was bound to subscriber', null=True)),
                ('bound_by_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which binding was performed', null=True)),
                ('is_bound', models.BooleanField(db_index=True, default=False, help_text='Whether user is permanently bound to a subscriber')),
                ('binding_method', models.CharField(choices=[('token', 'Token Validation'), ('admin', 'Admin Assignment'), ('migration', 'Data Migration')], default='token', help_text='How the binding was established', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['bound_subscriber_id', 'is_bound'], name='user_profil_bound_s_98b2aa_idx'), models.Index(fields=['user', 'is_bound'], name='user_profil_user_id_113d5b_idx')],
            },
        ),
    ]
