# Generated by Django 6.0.5 on 2026-09-01 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acctmgt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(db_index=True, help_text='6-digit verification code', max_length=6)),
                ('otp_type', models.CharField(choices=[('registration', 'Registration Verification'), ('password_reset', 'Password Reset')], db_index=True, default='registration', help_text='Purpose of the OTP token', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Timestamp when this OTP expires')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='True if this OTP has been successfully verified')),
                ('attempts', models.IntegerField(default=0, help_text='Number of failed validation attempts')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where OTP was requested', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification OTP',
                'verbose_name_plural': 'Email Verification OTPs',
                'db_table': 'email_verification_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'otp_type', 'is_verified', 'expires_at'], name='email_verif_user_id_5e22c3_idx')],
            },
        ),
    ]
