# Generated by Django 5.2.5 on 2025-12-08 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriber_id', models.AutoField(db_column='SubscriberID', primary_key=True, serialize=False)),
                ('subscriber_name', models.CharField(db_column='SubscriberName', max_length=255)),
            ],
            options={
                'db_table': 'Sheet1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriberToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(db_index=True, help_text='Reference to subscriber ID from external table')),
                ('token', models.CharField(help_text='URL-safe random string', max_length=32, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_used_for_binding', models.BooleanField(db_index=True, default=False, help_text='Whether this token has been used for permanent user-subscriber binding')),
                ('binding_date', models.DateTimeField(blank=True, help_text='When this token was used for binding', null=True)),
                ('binding_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which binding was performed', null=True)),
                ('bound_user', models.ForeignKey(blank=True, help_text='User who used this token for permanent binding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binding_tokens', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscriber Token',
                'verbose_name_plural': 'Subscriber Tokens',
                'db_table': 'subscriber_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscriber_id', 'is_active'], name='subscriber__subscri_c86767_idx'), models.Index(fields=['token', 'is_active'], name='subscriber__token_01d397_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(db_index=True, help_text='Reference to subscriber ID from external table')),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('awaiting_verification', 'Awaiting Verification'), ('finalizing', 'Finalizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('processing_stage', models.CharField(choices=[('pending', 'Pending'), ('upload_validation', 'File Upload & Validation'), ('data_mapping', 'Data Mapping & Preparation'), ('data_cleaning', 'Data Cleaning & Transformation'), ('credit_matching', 'Credit Matching & Classification'), ('awaiting_verification', 'Awaiting Human Verification'), ('post_verification', 'Finalization After Verification'), ('output_generation', 'Output Generation'), ('completed', 'Completed')], default='pending', help_text='Current processing stage for detailed progress tracking', max_length=50)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Overall progress percentage (0-100)')),
                ('current_message', models.TextField(blank=True, help_text='Current processing message for real-time updates')),
                ('activity_log', models.JSONField(blank=True, default=list, help_text='Timestamped log of processing activities for audit trail')),
                ('individual_records', models.PositiveIntegerField(default=0)),
                ('corporate_records', models.PositiveIntegerField(default=0)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('individual_credit_matched', models.PositiveIntegerField(default=0, help_text='Number of individual records with credit matches')),
                ('corporate_credit_matched', models.PositiveIntegerField(default=0, help_text='Number of corporate records with credit matches')),
                ('unmatched_credit_records', models.PositiveIntegerField(default=0, help_text='Number of credit records that could not be matched to any borrower')),
                ('excluded_individual_records', models.PositiveIntegerField(default=0, help_text='Number of individual records excluded during processing')),
                ('excluded_corporate_records', models.PositiveIntegerField(default=0, help_text='Number of corporate records excluded during processing')),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('has_verification_candidates', models.BooleanField(default=False, help_text='Whether this upload has records requiring human verification')),
                ('commercial_candidates_count', models.IntegerField(default=0, help_text='Number of potential commercial entities found in consumer records')),
                ('consumer_candidates_count', models.IntegerField(default=0, help_text='Number of potential consumer entities found in commercial records')),
                ('verification_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when human verification was completed', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('individual_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('corporate_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('individual_txt_path', models.CharField(blank=True, max_length=500, null=True)),
                ('corporate_txt_path', models.CharField(blank=True, max_length=500, null=True)),
                ('individual_output_format', models.CharField(blank=True, help_text="Output format for individual sheet: 'xlsx' or 'txt'", max_length=10, null=True)),
                ('corporate_output_format', models.CharField(blank=True, help_text="Output format for corporate sheet: 'xlsx' or 'txt'", max_length=10, null=True)),
                ('original_file_path', models.CharField(blank=True, help_text='Path to the original unmodified uploaded file for dispute resolution and audit purposes', max_length=500, null=True)),
                ('processing_data', models.TextField(blank=True, help_text='JSON storage for processing data when using async workflow', null=True)),
                ('reporting_month', models.IntegerField(blank=True, help_text='User-selected reporting month (1-12) for output filename generation', null=True)),
                ('reporting_year', models.IntegerField(blank=True, help_text='User-selected reporting year for output filename generation', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Session',
                'verbose_name_plural': 'Upload Sessions',
                'db_table': 'upload_sessions',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'uploaded_at'], name='upload_sess_user_id_92d5e7_idx'), models.Index(fields=['subscriber_id', 'uploaded_at'], name='upload_sess_subscri_b0439b_idx'), models.Index(fields=['status', 'uploaded_at'], name='upload_sess_status_d1e11a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscriberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(db_index=True, help_text='Reference to subscriber ID from external table')),
                ('permission_level', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read/Write'), ('admin', 'Administrator')], default='read', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscriber Permission',
                'verbose_name_plural': 'User Subscriber Permissions',
                'db_table': 'user_subscriber_permissions',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'subscriber_id', 'is_active'], name='user_subscr_user_id_68c5d8_idx'), models.Index(fields=['subscriber_id', 'is_active'], name='user_subscr_subscri_412b11_idx')],
                'unique_together': {('user', 'subscriber_id')},
            },
        ),
    ]
