# Generated by Django 5.2.5 on 2025-12-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='verification_skipped',
            field=models.BooleanField(default=False, help_text='Whether verification was auto-skipped due to no candidates'),
        ),
    ]
