# Generated by Django 5.2.5 on 2025-12-19 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_uploadsession_verification_skipped'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('awaiting_verification', 'Awaiting Verification'), ('finalizing', 'Finalizing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='User satisfaction rating (1-5 stars)')),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('general', 'General Feedback')], default='general', help_text='Type of feedback', max_length=20)),
                ('message', models.TextField(help_text='Detailed feedback message from user')),
                ('page_url', models.CharField(blank=True, help_text='URL of page where feedback was submitted', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin review')),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the feedback (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'db_table': 'user_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='user_feedba_categor_8123b4_idx'), models.Index(fields=['rating', 'created_at'], name='user_feedba_rating_eb30c4_idx'), models.Index(fields=['is_reviewed', 'created_at'], name='user_feedba_is_revi_81a36d_idx')],
            },
        ),
    ]
