# Generated by Django 5.2.5 on 2026-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_uploadsession_status_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.IntegerField(db_index=True, help_text='Reference to subscriber ID from external table', unique=True)),
                ('email', models.EmailField(help_text='Subscriber contact email for reports', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscriber Email',
                'verbose_name_plural': 'Subscriber Emails',
                'db_table': 'subscriber_emails',
            },
        ),
    ]
