# Generated by Django 5.2.5 on 2026-02-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_subscriberemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriberEmail',
        ),
    ]
