# Generated by Django 6.0.5 on 2026-07-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_delete_subscriberemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='file_password',
            field=models.CharField(blank=True, help_text='Password for encrypted Excel files', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='split_option',
            field=models.CharField(blank=True, default='split', help_text="User decision for merged files: 'split' or 'no_split'", max_length=20, null=True),
        ),
    ]
