"""
Django settings for fcbauto project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',
    'auto',
    'acctmgt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'acctmgt.middleware.SubscriberSessionMiddleware',  # Custom subscriber validation middleware
    #'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'fcbauto.urls'

INTERNAL_IPS = [
    '127.0.0.1',  # Localhost
    # You can add other IPs if needed, for example, if you're using Docker or a VM
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'acctmgt.context_processors.subscriber_context',  # Custom context processor for subscriber binding
            ],
        },
    },
]

WSGI_APPLICATION = 'fcbauto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Single MSSQL database configuration
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': config('DB_SUBSCRIBERS_NAME', default='Subscribers'),
        'HOST': config('DB_SUBSCRIBERS_HOST', default='O2JUNE\\SQLEXPRESS'),
        'USER': config('DB_SUBSCRIBERS_USER', default=''),
        'PASSWORD': config('DB_SUBSCRIBERS_PASSWORD', default=''),
        'PORT': config('DB_SUBSCRIBERS_PORT', default=''),
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'Trusted_connection': 'yes',
            'TrustServerCertificate': 'yes',
            'Encrypt': 'no',
        },
    }
}

# No database router needed - all models use the default MSSQL database
# DATABASE_ROUTERS = []


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'auto/static'),
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication settings
LOGIN_URL = 'acctmgt:login'  # Using the namespaced URL
LOGIN_REDIRECT_URL = 'auto:dashboard'  # Using the namespaced URL for dashboard
LOGOUT_REDIRECT_URL = 'acctmgt:login'  # Using the namespaced URL


# Django Q Cluster Configuration
Q_CLUSTER = {
    'name': 'credit_bureau_processing',
    'workers': 4,
    'recycle': 500,
    'timeout': 36000,  # 10 hours timeout for large file processing with chunking
    'retry': 37000,  # Retry window - must be larger than timeout (10 hours)
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',  # Use Django ORM as broker (SQLite)
    'catch_up': False,
    'save_limit': 250,
    'ack_failures': True,
    'max_attempts': 1,
    'attempt_count': 1,
}


# Logging Configuration
# Logs appear in terminal AND are saved to logs/app.log
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'auto': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'acctmgt': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
}


# =============================================================================
# CACHING CONFIGURATION
# Required for rate limiting functionality
# =============================================================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'fcbauto-rate-limit-cache',
    }
}


# =============================================================================
# RATE LIMITING CONFIGURATION
# Protects against abuse and ensures fair resource allocation
# =============================================================================
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_ENABLE = True


# =============================================================================
# EMAIL CONFIGURATION
# For feedback notifications and other email functionality
# =============================================================================
# Email recipient for feedback notifications
FEEDBACK_EMAIL_RECIPIENT = config('FEEDBACK_EMAIL_RECIPIENT', default='[EMAIL_ADDRESS]')

# Email backend configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='[EMAIL_ADDRESS]')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='[PASSWORD]')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='[EMAIL_ADDRESS]')
